function ddt = d_orbit(t, rv)

rho = norm(rv(1:3));

mu = 4.9048695e12;
ddt = [rv(4); ... 
       rv(5); ... 
       rv(6); ...
       -mu*rv(1)/(rho^3);...
       -mu*rv(2)/(rho^3);...
       -mu*rv(3)/(rho^3)];
end
